# Copyright 2021 dasm
# See LICENSE file for licensing details.
#
# TEMPLATE-TODO: change this example to suit your needs.
# If you don't need a config, you can remove the file entirely.
# It ties in to the example _on_config_changed handler in src/charm.py
#
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  cluster-name:
    type: string
    default: "opensearch-cluster"
    description: If the OpenSearch cluster name is not passed in the relation set it here.
  port:
    type: int
    default: 9200
    description: OpenSearch port
  perf-port:
    type: int
    default: 9600
    description: OpenSearch port for Performance Analyzer
  jvm-heap-size:
    type: string
    default: "512m"
    description: JVM Heap memory size (default 512m)
