# Copyright 2021 dasm
# See LICENSE file for licensing details.
#

options:
  cluster_name:
    type: string
    default: "opensearch-cluster"
    description: If the OpenSearch cluster name is not passed in the relation set it here.
  node_name:
    type: string
    default: "opensearch-node1"
    description: OpenSearch hostname
  discovery_seed_hosts:
    type: string
    default: "opensearch-node1"
    description: OpenSearch seed host
  type:
    type: string
    default: "single-node"
  jvm_heap_size:
    type: string
    default: "512m"
    description: JVM Heap memory size (default 512m)
