# Copyright 2021 dasm
# See LICENSE file for licensing details.
#

options:
  cluster-name:
    type: string
    default: "opensearch-cluster"
    description: If the OpenSearch cluster name is not passed in the relation set it here.
  node-name:
    type: string
    default: "opensearch-node1"
    description: OpenSearch hostname
  discovery-seed-hosts:
    type: string
    default: "opensearch-node1"
    description: OpenSearch seed host
  cluster-initial-master-nodes:
    type: string
    default: "opensearch-node1"
    description: Initial master node
  jvm-heap-size:
    type: string
    default: "512m"
    description: JVM Heap memory size (default 512m)
